### ISSUE TITLE
REQUEST FOR TARGET - T-MOTOR F7

### ISSUE THREAD

**Issue by FlyTilliDie** [emuflight/EmuFlight#76] opened 2020-01-28 00:42 UTC
Would love to have a target for the Tmotorf7. I'll gladly test it. I really prefer EMU over BF

**Comment by nerdCopter** [comment] 2020-02-14 14:36
is this a duplicate of #75 ?

**Comment by FlyTilliDie** [comment] 2020-03-01 21:00
> is this a duplicate of #75 ?


I think so. The difference is just the HD I believe. Not sure if that plus a part

**Comment by gretel** [comment] 2020-03-13 15:26
@Kaiowarez can you help out?

**Comment by Kaiowarez** [comment] 2020-03-13 15:29
Don't we have this? But I can make it later

**Comment by gretel** [comment] 2020-03-13 15:30
sorry i wasnt sure so many merges :) thank you!

**Comment by Kaiowarez** [comment] 2020-03-21 17:29
Should have this already, if not it's prolly on my repo needing testing lemme know if someone wants to work on getting this tested

**Comment by Kaiowarez** [comment] 2020-03-23 19:17
Done with target please close.

**Closed** 2020-03-23 19:19 UTC
Labels: enhancement
